Test
miolini/datacounter pull request #7
Opened 2022-12-28 22:36 UTC by davidnewhall

add workflow, remove travis

2022-12-28 22:37 UTC, davidnewhall commented
crap, wrong upstream. sorry. :(

2022-12-28 22:37 UTC, closed without merging

2022-12-28 22:40 UTC, miolini requested changes
Hi! I saw your package inside source code. Could you please change it to original.

2022-12-28 22:40 UTC, miolini commented on go.mod
> +module golift.io/datacounter
I cannot use this package name.

2022-12-28 22:40 UTC, miolini commented on reader_test.go
> +	"golift.io/datacounter"
Same, wrong package name.

2022-12-28 22:40 UTC, miolini commented on response_writer_test.go
> +	"golift.io/datacounter"
Cannot import this package.

2022-12-31 02:38 UTC, davidnewhall commented
Sorry, I forked your repo and have been maintaining my own copy of this code. I accidentally opened this PR against your repo instead of my own. Probably the second time I've done that. haha sorry.

2022-12-31 02:40 UTC, davidnewhall commented
And on that note, you're welcome to copy any of my changes. If you add in the two methods I forked your code to make I'll probably switch back.